name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          ssh -i ~/ssh_key ubuntu@16.170.168.106 -t "
            cd ~/bms &&
            git pull origin main &&

            export PATH=/home/ubuntu/.nvm/versions/node/v24.16.0/bin:\$PATH &&

            pnpm install &&
            pnpm run build &&

            pm2 restart http-server &&
            pm2 restart ws-server
          "